// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.24.2
// source: grpc/rulestone.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmptyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EmptyRequest) Reset() {
	*x = EmptyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_rulestone_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmptyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyRequest) ProtoMessage() {}

func (x *EmptyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_rulestone_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyRequest.ProtoReflect.Descriptor instead.
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return file_grpc_rulestone_proto_rawDescGZIP(), []int{0}
}

type EmptyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EmptyResponse) Reset() {
	*x = EmptyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_rulestone_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmptyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyResponse) ProtoMessage() {}

func (x *EmptyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_rulestone_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyResponse.ProtoReflect.Descriptor instead.
func (*EmptyResponse) Descriptor() ([]byte, []int) {
	return file_grpc_rulestone_proto_rawDescGZIP(), []int{1}
}

type RuleEngineRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RuleEngineId int32 `protobuf:"varint,1,opt,name=ruleEngineId,proto3" json:"ruleEngineId,omitempty"`
}

func (x *RuleEngineRequest) Reset() {
	*x = RuleEngineRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_rulestone_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RuleEngineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleEngineRequest) ProtoMessage() {}

func (x *RuleEngineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_rulestone_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleEngineRequest.ProtoReflect.Descriptor instead.
func (*RuleEngineRequest) Descriptor() ([]byte, []int) {
	return file_grpc_rulestone_proto_rawDescGZIP(), []int{2}
}

func (x *RuleEngineRequest) GetRuleEngineId() int32 {
	if x != nil {
		return x.RuleEngineId
	}
	return 0
}

type RuleEngineResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RuleEngineId int32 `protobuf:"varint,1,opt,name=ruleEngineId,proto3" json:"ruleEngineId,omitempty"`
}

func (x *RuleEngineResponse) Reset() {
	*x = RuleEngineResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_rulestone_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RuleEngineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleEngineResponse) ProtoMessage() {}

func (x *RuleEngineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_rulestone_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleEngineResponse.ProtoReflect.Descriptor instead.
func (*RuleEngineResponse) Descriptor() ([]byte, []int) {
	return file_grpc_rulestone_proto_rawDescGZIP(), []int{3}
}

func (x *RuleEngineResponse) GetRuleEngineId() int32 {
	if x != nil {
		return x.RuleEngineId
	}
	return 0
}

type RuleFromStringRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RuleEngineId int32  `protobuf:"varint,1,opt,name=ruleEngineId,proto3" json:"ruleEngineId,omitempty"`
	RuleString   string `protobuf:"bytes,2,opt,name=ruleString,proto3" json:"ruleString,omitempty"`
}

func (x *RuleFromStringRequest) Reset() {
	*x = RuleFromStringRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_rulestone_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RuleFromStringRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleFromStringRequest) ProtoMessage() {}

func (x *RuleFromStringRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_rulestone_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleFromStringRequest.ProtoReflect.Descriptor instead.
func (*RuleFromStringRequest) Descriptor() ([]byte, []int) {
	return file_grpc_rulestone_proto_rawDescGZIP(), []int{4}
}

func (x *RuleFromStringRequest) GetRuleEngineId() int32 {
	if x != nil {
		return x.RuleEngineId
	}
	return 0
}

func (x *RuleFromStringRequest) GetRuleString() string {
	if x != nil {
		return x.RuleString
	}
	return ""
}

type RuleFromFileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RuleEngineId int32  `protobuf:"varint,1,opt,name=ruleEngineId,proto3" json:"ruleEngineId,omitempty"`
	RuleFilePath string `protobuf:"bytes,2,opt,name=ruleFilePath,proto3" json:"ruleFilePath,omitempty"`
}

func (x *RuleFromFileRequest) Reset() {
	*x = RuleFromFileRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_rulestone_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RuleFromFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleFromFileRequest) ProtoMessage() {}

func (x *RuleFromFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_rulestone_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleFromFileRequest.ProtoReflect.Descriptor instead.
func (*RuleFromFileRequest) Descriptor() ([]byte, []int) {
	return file_grpc_rulestone_proto_rawDescGZIP(), []int{5}
}

func (x *RuleFromFileRequest) GetRuleEngineId() int32 {
	if x != nil {
		return x.RuleEngineId
	}
	return 0
}

func (x *RuleFromFileRequest) GetRuleFilePath() string {
	if x != nil {
		return x.RuleFilePath
	}
	return ""
}

type RuleFromDirectoryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RuleEngineId       int32  `protobuf:"varint,1,opt,name=ruleEngineId,proto3" json:"ruleEngineId,omitempty"`
	RulesDirectoryPath string `protobuf:"bytes,2,opt,name=rulesDirectoryPath,proto3" json:"rulesDirectoryPath,omitempty"`
}

func (x *RuleFromDirectoryRequest) Reset() {
	*x = RuleFromDirectoryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_rulestone_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RuleFromDirectoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleFromDirectoryRequest) ProtoMessage() {}

func (x *RuleFromDirectoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_rulestone_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleFromDirectoryRequest.ProtoReflect.Descriptor instead.
func (*RuleFromDirectoryRequest) Descriptor() ([]byte, []int) {
	return file_grpc_rulestone_proto_rawDescGZIP(), []int{6}
}

func (x *RuleFromDirectoryRequest) GetRuleEngineId() int32 {
	if x != nil {
		return x.RuleEngineId
	}
	return 0
}

func (x *RuleFromDirectoryRequest) GetRulesDirectoryPath() string {
	if x != nil {
		return x.RulesDirectoryPath
	}
	return ""
}

type RuleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RuleId int32 `protobuf:"varint,1,opt,name=ruleId,proto3" json:"ruleId,omitempty"`
}

func (x *RuleResponse) Reset() {
	*x = RuleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_rulestone_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleResponse) ProtoMessage() {}

func (x *RuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_rulestone_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleResponse.ProtoReflect.Descriptor instead.
func (*RuleResponse) Descriptor() ([]byte, []int) {
	return file_grpc_rulestone_proto_rawDescGZIP(), []int{7}
}

func (x *RuleResponse) GetRuleId() int32 {
	if x != nil {
		return x.RuleId
	}
	return 0
}

type NumRulesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NumRules int32 `protobuf:"varint,1,opt,name=numRules,proto3" json:"numRules,omitempty"`
}

func (x *NumRulesResponse) Reset() {
	*x = NumRulesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_rulestone_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NumRulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumRulesResponse) ProtoMessage() {}

func (x *NumRulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_rulestone_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumRulesResponse.ProtoReflect.Descriptor instead.
func (*NumRulesResponse) Descriptor() ([]byte, []int) {
	return file_grpc_rulestone_proto_rawDescGZIP(), []int{8}
}

func (x *NumRulesResponse) GetNumRules() int32 {
	if x != nil {
		return x.NumRules
	}
	return 0
}

type RulesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RuleIds []int32 `protobuf:"varint,1,rep,packed,name=ruleIds,proto3" json:"ruleIds,omitempty"`
}

func (x *RulesResponse) Reset() {
	*x = RulesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_rulestone_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RulesResponse) ProtoMessage() {}

func (x *RulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_rulestone_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RulesResponse.ProtoReflect.Descriptor instead.
func (*RulesResponse) Descriptor() ([]byte, []int) {
	return file_grpc_rulestone_proto_rawDescGZIP(), []int{9}
}

func (x *RulesResponse) GetRuleIds() []int32 {
	if x != nil {
		return x.RuleIds
	}
	return nil
}

type MatchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId    int64  `protobuf:"varint,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	RuleEngineId int32  `protobuf:"varint,2,opt,name=ruleEngineId,proto3" json:"ruleEngineId,omitempty"`
	JsonData     string `protobuf:"bytes,3,opt,name=jsonData,proto3" json:"jsonData,omitempty"`
}

func (x *MatchRequest) Reset() {
	*x = MatchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_rulestone_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchRequest) ProtoMessage() {}

func (x *MatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_rulestone_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchRequest.ProtoReflect.Descriptor instead.
func (*MatchRequest) Descriptor() ([]byte, []int) {
	return file_grpc_rulestone_proto_rawDescGZIP(), []int{10}
}

func (x *MatchRequest) GetRequestId() int64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *MatchRequest) GetRuleEngineId() int32 {
	if x != nil {
		return x.RuleEngineId
	}
	return 0
}

func (x *MatchRequest) GetJsonData() string {
	if x != nil {
		return x.JsonData
	}
	return ""
}

type MatchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId int64   `protobuf:"varint,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	MatchIds  []int32 `protobuf:"varint,2,rep,packed,name=matchIds,proto3" json:"matchIds,omitempty"`
}

func (x *MatchResponse) Reset() {
	*x = MatchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_rulestone_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchResponse) ProtoMessage() {}

func (x *MatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_rulestone_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchResponse.ProtoReflect.Descriptor instead.
func (*MatchResponse) Descriptor() ([]byte, []int) {
	return file_grpc_rulestone_proto_rawDescGZIP(), []int{11}
}

func (x *MatchResponse) GetRequestId() int64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *MatchResponse) GetMatchIds() []int32 {
	if x != nil {
		return x.MatchIds
	}
	return nil
}

var File_grpc_rulestone_proto protoreflect.FileDescriptor

var file_grpc_rulestone_proto_rawDesc = []byte{
	0x0a, 0x14, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x72, 0x75, 0x6c, 0x65, 0x73, 0x74, 0x6f, 0x6e, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x72, 0x75, 0x6c, 0x65, 0x73, 0x74, 0x6f, 0x6e,
	0x65, 0x22, 0x0e, 0x0a, 0x0c, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x0f, 0x0a, 0x0d, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x37, 0x0a, 0x11, 0x52, 0x75, 0x6c, 0x65, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x72, 0x75, 0x6c, 0x65, 0x45,
	0x6e, 0x67, 0x69, 0x6e, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x72,
	0x75, 0x6c, 0x65, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x49, 0x64, 0x22, 0x38, 0x0a, 0x12, 0x52,
	0x75, 0x6c, 0x65, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x22, 0x0a, 0x0c, 0x72, 0x75, 0x6c, 0x65, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x72, 0x75, 0x6c, 0x65, 0x45, 0x6e, 0x67,
	0x69, 0x6e, 0x65, 0x49, 0x64, 0x22, 0x5b, 0x0a, 0x15, 0x52, 0x75, 0x6c, 0x65, 0x46, 0x72, 0x6f,
	0x6d, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22,
	0x0a, 0x0c, 0x72, 0x75, 0x6c, 0x65, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x72, 0x75, 0x6c, 0x65, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65,
	0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x75, 0x6c, 0x65, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x75, 0x6c, 0x65, 0x53, 0x74, 0x72, 0x69,
	0x6e, 0x67, 0x22, 0x5d, 0x0a, 0x13, 0x52, 0x75, 0x6c, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x46, 0x69,
	0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x72, 0x75, 0x6c,
	0x65, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0c, 0x72, 0x75, 0x6c, 0x65, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x49, 0x64, 0x12, 0x22, 0x0a,
	0x0c, 0x72, 0x75, 0x6c, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x75, 0x6c, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x74,
	0x68, 0x22, 0x6e, 0x0a, 0x18, 0x52, 0x75, 0x6c, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x44, 0x69, 0x72,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a,
	0x0c, 0x72, 0x75, 0x6c, 0x65, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0c, 0x72, 0x75, 0x6c, 0x65, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x49,
	0x64, 0x12, 0x2e, 0x0a, 0x12, 0x72, 0x75, 0x6c, 0x65, 0x73, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74,
	0x6f, 0x72, 0x79, 0x50, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x72,
	0x75, 0x6c, 0x65, 0x73, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x50, 0x61, 0x74,
	0x68, 0x22, 0x26, 0x0a, 0x0c, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x75, 0x6c, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x72, 0x75, 0x6c, 0x65, 0x49, 0x64, 0x22, 0x2e, 0x0a, 0x10, 0x4e, 0x75, 0x6d,
	0x52, 0x75, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x6e, 0x75, 0x6d, 0x52, 0x75, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x6e, 0x75, 0x6d, 0x52, 0x75, 0x6c, 0x65, 0x73, 0x22, 0x29, 0x0a, 0x0d, 0x52, 0x75, 0x6c,
	0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x75,
	0x6c, 0x65, 0x49, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x07, 0x72, 0x75, 0x6c,
	0x65, 0x49, 0x64, 0x73, 0x22, 0x6c, 0x0a, 0x0c, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x72, 0x75, 0x6c, 0x65, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x72, 0x75, 0x6c, 0x65, 0x45, 0x6e,
	0x67, 0x69, 0x6e, 0x65, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6a, 0x73, 0x6f, 0x6e, 0x44, 0x61,
	0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6a, 0x73, 0x6f, 0x6e, 0x44, 0x61,
	0x74, 0x61, 0x22, 0x49, 0x0a, 0x0d, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x49, 0x64, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x05, 0x52, 0x08, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x49, 0x64, 0x73, 0x32, 0xb9, 0x04,
	0x0a, 0x10, 0x52, 0x75, 0x6c, 0x65, 0x73, 0x74, 0x6f, 0x6e, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x4a, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x75, 0x6c, 0x65,
	0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x12, 0x17, 0x2e, 0x72, 0x75, 0x6c, 0x65, 0x73, 0x74, 0x6f,
	0x6e, 0x65, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1d, 0x2e, 0x72, 0x75, 0x6c, 0x65, 0x73, 0x74, 0x6f, 0x6e, 0x65, 0x2e, 0x52, 0x75, 0x6c, 0x65,
	0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x52,
	0x0a, 0x15, 0x41, 0x64, 0x64, 0x52, 0x75, 0x6c, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x4a, 0x73, 0x6f,
	0x6e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x20, 0x2e, 0x72, 0x75, 0x6c, 0x65, 0x73, 0x74,
	0x6f, 0x6e, 0x65, 0x2e, 0x52, 0x75, 0x6c, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x53, 0x74, 0x72, 0x69,
	0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x72, 0x75, 0x6c, 0x65,
	0x73, 0x74, 0x6f, 0x6e, 0x65, 0x2e, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x52, 0x0a, 0x15, 0x41, 0x64, 0x64, 0x52, 0x75, 0x6c, 0x65, 0x46, 0x72, 0x6f,
	0x6d, 0x59, 0x61, 0x6d, 0x6c, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x20, 0x2e, 0x72, 0x75,
	0x6c, 0x65, 0x73, 0x74, 0x6f, 0x6e, 0x65, 0x2e, 0x52, 0x75, 0x6c, 0x65, 0x46, 0x72, 0x6f, 0x6d,
	0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e,
	0x72, 0x75, 0x6c, 0x65, 0x73, 0x74, 0x6f, 0x6e, 0x65, 0x2e, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4e, 0x0a, 0x13, 0x41, 0x64, 0x64, 0x52, 0x75, 0x6c,
	0x65, 0x46, 0x72, 0x6f, 0x6d, 0x46, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x12, 0x1e, 0x2e,
	0x72, 0x75, 0x6c, 0x65, 0x73, 0x74, 0x6f, 0x6e, 0x65, 0x2e, 0x52, 0x75, 0x6c, 0x65, 0x46, 0x72,
	0x6f, 0x6d, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e,
	0x72, 0x75, 0x6c, 0x65, 0x73, 0x74, 0x6f, 0x6e, 0x65, 0x2e, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5d, 0x0a, 0x19, 0x41, 0x64, 0x64, 0x52, 0x75, 0x6c,
	0x65, 0x73, 0x46, 0x72, 0x6f, 0x6d, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x50,
	0x61, 0x74, 0x68, 0x12, 0x23, 0x2e, 0x72, 0x75, 0x6c, 0x65, 0x73, 0x74, 0x6f, 0x6e, 0x65, 0x2e,
	0x52, 0x75, 0x6c, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x72, 0x75, 0x6c, 0x65, 0x73,
	0x74, 0x6f, 0x6e, 0x65, 0x2e, 0x4e, 0x75, 0x6d, 0x52, 0x75, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x42, 0x0a, 0x08, 0x41, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74,
	0x65, 0x12, 0x1c, 0x2e, 0x72, 0x75, 0x6c, 0x65, 0x73, 0x74, 0x6f, 0x6e, 0x65, 0x2e, 0x52, 0x75,
	0x6c, 0x65, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x18, 0x2e, 0x72, 0x75, 0x6c, 0x65, 0x73, 0x74, 0x6f, 0x6e, 0x65, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x05, 0x4d, 0x61, 0x74,
	0x63, 0x68, 0x12, 0x17, 0x2e, 0x72, 0x75, 0x6c, 0x65, 0x73, 0x74, 0x6f, 0x6e, 0x65, 0x2e, 0x4d,
	0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x72, 0x75,
	0x6c, 0x65, 0x73, 0x74, 0x6f, 0x6e, 0x65, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x30, 0x01, 0x42, 0x4c, 0x0a, 0x1d, 0x63, 0x6f, 0x6d,
	0x2e, 0x61, 0x74, 0x6c, 0x61, 0x73, 0x67, 0x75, 0x72, 0x75, 0x73, 0x2e, 0x72, 0x75, 0x6c, 0x65,
	0x73, 0x74, 0x6f, 0x6e, 0x65, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x71, 0x75, 0x69, 0x63, 0x6b, 0x73, 0x68, 0x6f, 0x72,
	0x65, 0x2f, 0x72, 0x75, 0x6c, 0x65, 0x73, 0x74, 0x6f, 0x6e, 0x65, 0x2d, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_rulestone_proto_rawDescOnce sync.Once
	file_grpc_rulestone_proto_rawDescData = file_grpc_rulestone_proto_rawDesc
)

func file_grpc_rulestone_proto_rawDescGZIP() []byte {
	file_grpc_rulestone_proto_rawDescOnce.Do(func() {
		file_grpc_rulestone_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_rulestone_proto_rawDescData)
	})
	return file_grpc_rulestone_proto_rawDescData
}

var file_grpc_rulestone_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_grpc_rulestone_proto_goTypes = []interface{}{
	(*EmptyRequest)(nil),             // 0: rulestone.EmptyRequest
	(*EmptyResponse)(nil),            // 1: rulestone.EmptyResponse
	(*RuleEngineRequest)(nil),        // 2: rulestone.RuleEngineRequest
	(*RuleEngineResponse)(nil),       // 3: rulestone.RuleEngineResponse
	(*RuleFromStringRequest)(nil),    // 4: rulestone.RuleFromStringRequest
	(*RuleFromFileRequest)(nil),      // 5: rulestone.RuleFromFileRequest
	(*RuleFromDirectoryRequest)(nil), // 6: rulestone.RuleFromDirectoryRequest
	(*RuleResponse)(nil),             // 7: rulestone.RuleResponse
	(*NumRulesResponse)(nil),         // 8: rulestone.NumRulesResponse
	(*RulesResponse)(nil),            // 9: rulestone.RulesResponse
	(*MatchRequest)(nil),             // 10: rulestone.MatchRequest
	(*MatchResponse)(nil),            // 11: rulestone.MatchResponse
}
var file_grpc_rulestone_proto_depIdxs = []int32{
	0,  // 0: rulestone.RulestoneService.CreateRuleEngine:input_type -> rulestone.EmptyRequest
	4,  // 1: rulestone.RulestoneService.AddRuleFromJsonString:input_type -> rulestone.RuleFromStringRequest
	4,  // 2: rulestone.RulestoneService.AddRuleFromYamlString:input_type -> rulestone.RuleFromStringRequest
	5,  // 3: rulestone.RulestoneService.AddRuleFromFilePath:input_type -> rulestone.RuleFromFileRequest
	6,  // 4: rulestone.RulestoneService.AddRulesFromDirectoryPath:input_type -> rulestone.RuleFromDirectoryRequest
	2,  // 5: rulestone.RulestoneService.Activate:input_type -> rulestone.RuleEngineRequest
	10, // 6: rulestone.RulestoneService.Match:input_type -> rulestone.MatchRequest
	3,  // 7: rulestone.RulestoneService.CreateRuleEngine:output_type -> rulestone.RuleEngineResponse
	7,  // 8: rulestone.RulestoneService.AddRuleFromJsonString:output_type -> rulestone.RuleResponse
	7,  // 9: rulestone.RulestoneService.AddRuleFromYamlString:output_type -> rulestone.RuleResponse
	7,  // 10: rulestone.RulestoneService.AddRuleFromFilePath:output_type -> rulestone.RuleResponse
	8,  // 11: rulestone.RulestoneService.AddRulesFromDirectoryPath:output_type -> rulestone.NumRulesResponse
	1,  // 12: rulestone.RulestoneService.Activate:output_type -> rulestone.EmptyResponse
	11, // 13: rulestone.RulestoneService.Match:output_type -> rulestone.MatchResponse
	7,  // [7:14] is the sub-list for method output_type
	0,  // [0:7] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_rulestone_proto_init() }
func file_grpc_rulestone_proto_init() {
	if File_grpc_rulestone_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_rulestone_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmptyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_rulestone_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmptyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_rulestone_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RuleEngineRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_rulestone_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RuleEngineResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_rulestone_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RuleFromStringRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_rulestone_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RuleFromFileRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_rulestone_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RuleFromDirectoryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_rulestone_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RuleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_rulestone_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NumRulesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_rulestone_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RulesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_rulestone_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MatchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_rulestone_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MatchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_rulestone_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_rulestone_proto_goTypes,
		DependencyIndexes: file_grpc_rulestone_proto_depIdxs,
		MessageInfos:      file_grpc_rulestone_proto_msgTypes,
	}.Build()
	File_grpc_rulestone_proto = out.File
	file_grpc_rulestone_proto_rawDesc = nil
	file_grpc_rulestone_proto_goTypes = nil
	file_grpc_rulestone_proto_depIdxs = nil
}
